const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Piso: 0},
	{Vida: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Dinossauro: 0},
	{Teclado: 0},
	{Projétil: 0},
	{ComidaSaudavel: 0},
	{ComidaRuim: 0},
	{BarraDeVida: 0},
	{TextoFalta: 0},
	{ComidaSaudavel2: 0},
	{ComidaSaudavel3: 0},
	{ComidaRuim2: 0},
	{ComidaRuim3: 0},
	{GameOver: 0},
	{GameOverTexto: 0},
	{TextoPontos: 0},
	{Áudio: 0},
	{BotaoStart: 0},
	{Mouse: 0},
	{textoBoasVindas: 0},
	{Fundo: 0},
	{Fundo2: 0},
	{Toque: 0},
	{Seta_esquerda: 0},
	{seta_direita: 0},
	{AJAX: 0},
	{Faltas: 0},
	{Pontos: 0}
];

self.InstanceType = {
	Piso: class extends self.ISpriteInstance {},
	Dinossauro: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	ComidaSaudavel: class extends self.ISpriteInstance {},
	ComidaRuim: class extends self.ISpriteInstance {},
	BarraDeVida: class extends self.ISpriteInstance {},
	TextoFalta: class extends self.ITextInstance {},
	ComidaSaudavel2: class extends self.ISpriteInstance {},
	ComidaSaudavel3: class extends self.ISpriteInstance {},
	ComidaRuim2: class extends self.ISpriteInstance {},
	ComidaRuim3: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	GameOverTexto: class extends self.ITextInstance {},
	TextoPontos: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	BotaoStart: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	textoBoasVindas: class extends self.ISpriteInstance {},
	Fundo: class extends self.ISpriteInstance {},
	Fundo2: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Seta_esquerda: class extends self.ISpriteInstance {},
	seta_direita: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {}
}