const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.TemplateName,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Timer.Cnds.IsTimerPaused,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{hasHamburger: 0},
	{Grill: 0},
	{orderSpeed: 0},
	{orderTimer: 0},
	{Timer: 0},
	{Orders: 0},
	{maxOrderTimer: 0},
	{Sine: 0},
	{Order: 0},
	{grillTime: 0},
	{placed: 0},
	{DragDrop: 0},
	{Ingredient: 0},
	{IngredientSlot: 0},
	{BreadSlot: 0},
	{ServeSlot: 0},
	{TextScore: 0},
	{hasTomato: 0},
	{hasLettuce: 0},
	{hasCheese: 0},
	{Bread: 0},
	{Touch: 0},
	{Tween: 0},
	{Smoke: 0},
	{TextLives: 0},
	{Fader: 0},
	{TextGameOver: 0},
	{TextTutorial: 0},
	{TutorialImage: 0},
	{TutorialButton: 0},
	{Icons: 0},
	{Background: 0},
	{Fundo: 0},
	{BotaoIniciar: 0},
	{score: 0},
	{lives: 0},
	{gameOver: 0},
	{slot: 0},
	{breadOrderValue: 0}
];

self.InstanceType = {
	Grill: class extends self.ISpriteInstance {},
	Orders: class extends self.ISpriteInstance {},
	Order: class extends self.ISpriteInstance {},
	Ingredient: class extends self.ISpriteInstance {},
	IngredientSlot: class extends self.ISpriteInstance {},
	BreadSlot: class extends self.ISpriteInstance {},
	ServeSlot: class extends self.ISpriteInstance {},
	TextScore: class extends self.ITextInstance {},
	Bread: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Smoke: class extends self.ISpriteInstance {},
	TextLives: class extends self.ITextInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextGameOver: class extends self.ITextInstance {},
	TextTutorial: class extends self.ITextInstance {},
	TutorialImage: class extends self.ISpriteInstance {},
	TutorialButton: class extends self.ISpriteInstance {},
	Icons: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Fundo: class extends self.ISpriteInstance {},
	BotaoIniciar: class extends self.ISpriteInstance {}
}