const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData
	];
};
self.C3_JsPropNameTable = [
	{frame: 0},
	{newframe: 0},
	{Picked: 0},
	{cards: 0},
	{backCards: 0},
	{Touch: 0},
	{Text: 0},
	{matches: 0},
	{Array: 0},
	{AJAX: 0},
	{LocalStorage: 0},
	{ArrayMatch: 0},
	{Button: 0},
	{Text2: 0},
	{Fase: 0},
	{VarChoose: 0},
	{VarTurns: 0},
	{VarPoints: 0},
	{VarStartGame: 0},
	{Jogo_ID: 0},
	{Pontos: 0}
];

self.InstanceType = {
	cards: class extends self.ISpriteInstance {},
	backCards: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	matches: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	ArrayMatch: class extends self.IArrayInstance {},
	Button: class extends self.IButtonInstance {},
	Text2: class extends self.ITextInstance {},
	Fase: class extends self.ITextInstance {}
}